apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronos-email

spec:
  replicas: 1

  selector:
    matchLabels:
      app: chronos-email

  template:
    metadata:
      labels:
        app: chronos-email

    spec:
      containers:
        - name: email

          image: 280480953008.dkr.ecr.us-west-2.amazonaws.com/chronos-dev:email-v1

          ports:
            - containerPort: 8080

          envFrom:
            - secretRef:
                name: chronos-email-db

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: chronos-email

spec:
  selector:
    app: chronos-email

  ports:
    - port: 8080
      targetPort: 8080

  type: ClusterIP